/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculty;

import cms.login.LoginForm;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class addfaculty extends javax.swing.JFrame {
public String gender;
String path=null;
byte[] userimage=null;
    /**
     * Creates new form addfaculty
     */
    public addfaculty() {
        initComponents();
        Connect();
        int id = id();
        txt_id.setText(Integer.toString(id));
    }

    /*********************************************************************/
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/cms", "root", "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /***********************************************************************/
    public int id() {
        int id = 0;
        try {
            pst = con.prepareStatement("SELECT MAX(id) from faculty");
            rs = pst.executeQuery();
            if (rs.next() == true) {
                id = rs.getInt(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return id + 1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_dob = new com.toedter.calendar.JDateChooser();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        txt_mail = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_image = new javax.swing.JLabel();
        choose_pic_bttn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_doj = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        position_combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_qualification = new javax.swing.JTextField();
        txt_experience = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Faculty Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_name.setForeground(new java.awt.Color(153, 153, 153));
        txt_name.setText("Faculty Name");
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });
        jPanel3.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        txt_dob.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, 30));

        female.setBackground(new java.awt.Color(152, 201, 45));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(152, 201, 45));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        male.setBackground(new java.awt.Color(152, 201, 45));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(152, 201, 45));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        txt_mail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(153, 153, 153));
        txt_mail.setText("Email");
        txt_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mailFocusLost(evt);
            }
        });
        jPanel3.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 50));

        txt_address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_address.setForeground(new java.awt.Color(153, 153, 153));
        txt_address.setText("Address");
        txt_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_addressFocusLost(evt);
            }
        });
        jPanel3.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, 90));

        txt_phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(153, 153, 153));
        txt_phone.setText("Contact Number");
        txt_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_phoneFocusLost(evt);
            }
        });
        jPanel3.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 30));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopPane1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 180));

        jPanel3.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, 200));

        choose_pic_bttn.setBackground(new java.awt.Color(152, 201, 45));
        choose_pic_bttn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        choose_pic_bttn.setText("Choose Pic");
        choose_pic_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        choose_pic_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choose_pic_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_pic_bttnActionPerformed(evt);
            }
        });
        jPanel3.add(choose_pic_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date Of Birth");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 580, 420));

        jPanel4.setBackground(new java.awt.Color(31, 36, 42));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_id.setForeground(new java.awt.Color(255, 51, 51));
        txt_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idFocusLost(evt);
            }
        });
        jPanel4.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Faculty Id");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txt_doj.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txt_doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Position");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date Of Joining");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        position_combo.setBackground(new java.awt.Color(152, 201, 45));
        position_combo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        position_combo.setForeground(new java.awt.Color(255, 255, 255));
        position_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Position--", "Full Professor", "Associate Professor", "Assistant Professor", "Lecturer", "Lab Assitant" }));
        jPanel4.add(position_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 170, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 350, 140));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Educational Details");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("School Details");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Personal Details");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(31, 36, 42));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_qualification.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_qualification.setForeground(new java.awt.Color(153, 153, 153));
        txt_qualification.setText("Qualification");
        txt_qualification.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_qualificationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qualificationFocusLost(evt);
            }
        });
        jPanel5.add(txt_qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 40));

        txt_experience.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_experience.setForeground(new java.awt.Color(153, 153, 153));
        txt_experience.setText("Experience");
        txt_experience.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_experienceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_experienceFocusLost(evt);
            }
        });
        txt_experience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_experienceActionPerformed(evt);
            }
        });
        jPanel5.add(txt_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 350, 150));

        cancel.setBackground(new java.awt.Color(152, 201, 45));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 130, -1));

        submit.setBackground(new java.awt.Color(152, 201, 45));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 980, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusGained
        if (txt_name.getText().equals("Faculty Name")) {
            txt_name.setText("");
            txt_name.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_nameFocusGained

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost
        if (txt_name.getText().equals("")) {
            txt_name.setText("Faculty Name");
            txt_name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_nameFocusLost

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender="female";
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender="male";
    }//GEN-LAST:event_maleActionPerformed

    private void txt_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusGained
        if (txt_mail.getText().equals("Email")) {
            txt_mail.setText("");
            txt_mail.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_mailFocusGained

    private void txt_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusLost
        if (txt_mail.getText().equals("")) {
            txt_mail.setText("Email");
            txt_mail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_mailFocusLost

    private void txt_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusGained
        if (txt_address.getText().equals("Address")) {
            txt_address.setText("");
            txt_address.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_addressFocusGained

    private void txt_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusLost
        if (txt_address.getText().equals("")) {
            txt_address.setText("Address");
            txt_address.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_addressFocusLost

    private void txt_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusGained
        if (txt_phone.getText().equals("Contact Number")) {
            txt_phone.setText("");
            txt_phone.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_phoneFocusGained

    private void txt_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusLost
        if (txt_phone.getText().equals("")) {
            txt_phone.setText("Contact Number");
            txt_phone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_phoneFocusLost

    private void choose_pic_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_pic_bttnActionPerformed
        JFileChooser picchooser=new JFileChooser();
        picchooser.setDialogTitle("Select Image");
        picchooser.showOpenDialog(null);
        File pic=picchooser.getSelectedFile();
        path= pic.getAbsolutePath();
        ImageIcon icon=new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
        lbl_image.setIcon(icon);
        try{
            File image = new File(path);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos= new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for(int readNum; (readNum=fis.read(buff)) !=-1 ; ){
                baos.write(buff,0,readNum);
            }
            userimage=baos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_choose_pic_bttnActionPerformed

    private void txt_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusGained

    }//GEN-LAST:event_txt_idFocusGained

    private void txt_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idFocusLost

    }//GEN-LAST:event_txt_idFocusLost

    private void txt_qualificationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qualificationFocusGained
        if (txt_qualification.getText().equals("Qualification")) {
            txt_qualification.setText("");
            txt_qualification.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_qualificationFocusGained

    private void txt_qualificationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qualificationFocusLost
        if (txt_qualification.getText().equals("")) {
            txt_qualification.setText("Qualification");
            txt_qualification.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_qualificationFocusLost

    private void txt_experienceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_experienceFocusGained
        if (txt_experience.getText().equals("Experience")) {
            txt_experience.setText("");
            txt_experience.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_experienceFocusGained

    private void txt_experienceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_experienceFocusLost
        if (txt_experience.getText().equals("")) {
            txt_experience.setText("Experience");
            txt_experience.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_experienceFocusLost

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       faculty f=new faculty();
       f.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_cancelActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        int id=Integer.parseInt(txt_id.getText());
        String facultyname=txt_name.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("YYYY-MM-dd");
        String dob=sdf.format(txt_dob.getDate());
        String email=txt_mail.getText();
        String address=txt_address.getText();
        String contact=txt_phone.getText();
        SimpleDateFormat sd=new SimpleDateFormat("YYYY-MM-dd");
        String joiningdate=sd.format(txt_doj.getDate());
        String position=position_combo.getSelectedItem().toString();
        String qualification=txt_qualification.getText();
        String experience=txt_experience.getText();

        try {
            pst = con.prepareStatement("insert into faculty (id,facultyname,dob,gender,email,address,contact,joiningdate,"
                    + "position,qualification,experience,pic)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?);");
            pst.setInt(1, id);
            pst.setString(2, facultyname);
            pst.setString(3, dob);
            pst.setString(4, gender);
            pst.setString(5, email);
            pst.setString(6, address);
            pst.setString(7, contact);
            pst.setString(8, joiningdate);
            
             pst.setString(9, position);
            pst.setString(10, qualification);
            pst.setString(11, experience);
            pst.setBytes(12, userimage);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Faculty Added Successfully!!");

            /**
            * coding for clearing the form fname.setText("");
            * lname.setText(""); mail.setText(""); txt_user.setText("");
            * security_ques.setSelectedIndex(-1); security_ans.setText("");
            * pass.setText(""); fname.requestFocus();
            */

        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void txt_experienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_experienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_experienceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addfaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JButton choose_pic_bttn;
    private javax.swing.JRadioButton female;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> position_combo;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txt_address;
    private com.toedter.calendar.JDateChooser txt_dob;
    private com.toedter.calendar.JDateChooser txt_doj;
    private javax.swing.JTextField txt_experience;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_qualification;
    // End of variables declaration//GEN-END:variables
}
