/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculty;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class facultydetail extends javax.swing.JFrame {
public String gender;
String path=null;
byte[] userimage=null;
    /**
     * Creates new form facultydetail
     */
    public facultydetail() {
        initComponents();
        Connect();
    }
/*********************************************************************/
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/cms", "root", "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(facultydetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(facultydetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /***********************************************************************/
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        txt_mail = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_image = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_doa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_doj = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_position = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_subject = new javax.swing.JLabel();
        lbl_sem = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_qualification = new javax.swing.JTextField();
        txt_experience = new javax.swing.JTextField();
        back_bttn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Faculty Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_name.setForeground(new java.awt.Color(153, 153, 153));
        txt_name.setText("Faculty Name");
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });
        jPanel3.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        female.setBackground(new java.awt.Color(152, 201, 45));
        female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(152, 201, 45));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        male.setBackground(new java.awt.Color(152, 201, 45));
        male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(152, 201, 45));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        txt_mail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(153, 153, 153));
        txt_mail.setText("Email");
        txt_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mailFocusLost(evt);
            }
        });
        jPanel3.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 50));

        txt_address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_address.setForeground(new java.awt.Color(153, 153, 153));
        txt_address.setText("Address");
        txt_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_addressFocusLost(evt);
            }
        });
        jPanel3.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, 90));

        txt_phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(153, 153, 153));
        txt_phone.setText("Contact Number");
        txt_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_phoneFocusLost(evt);
            }
        });
        jPanel3.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 30));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopPane1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 180));

        jPanel3.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, 200));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date Of Birth");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel3.add(lbl_doa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date Of Joining");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        jPanel3.add(lbl_doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 150, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 580, 420));

        jPanel4.setBackground(new java.awt.Color(31, 36, 42));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Faculty Id");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Subject Assign");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lbl_id.setBackground(new java.awt.Color(31, 36, 42));
        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 51, 51));
        jPanel4.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Position");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lbl_position.setBackground(new java.awt.Color(31, 36, 42));
        lbl_position.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_position.setForeground(new java.awt.Color(51, 204, 0));
        jPanel4.add(lbl_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 220, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Semester");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Course");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl_subject.setBackground(new java.awt.Color(31, 36, 42));
        lbl_subject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_subject.setForeground(new java.awt.Color(255, 51, 255));
        jPanel4.add(lbl_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 30));

        lbl_sem.setBackground(new java.awt.Color(31, 36, 42));
        lbl_sem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sem.setForeground(new java.awt.Color(0, 204, 204));
        jPanel4.add(lbl_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 30));

        lbl_course.setBackground(new java.awt.Color(31, 36, 42));
        lbl_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(255, 102, 102));
        jPanel4.add(lbl_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 350, 220));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Educational Details");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("School Details");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Personal Details");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(31, 36, 42));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_qualification.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_qualification.setForeground(new java.awt.Color(153, 153, 153));
        txt_qualification.setText("Qualification");
        txt_qualification.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_qualificationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qualificationFocusLost(evt);
            }
        });
        jPanel5.add(txt_qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 40));

        txt_experience.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_experience.setForeground(new java.awt.Color(153, 153, 153));
        txt_experience.setText("Experience");
        txt_experience.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_experienceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_experienceFocusLost(evt);
            }
        });
        txt_experience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_experienceActionPerformed(evt);
            }
        });
        jPanel5.add(txt_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 320, 150));

        back_bttn.setBackground(new java.awt.Color(152, 201, 45));
        back_bttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_bttn.setText("Back");
        back_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, 30));

        txt_search.setBackground(new java.awt.Color(21, 25, 28));
        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_search.setForeground(new java.awt.Color(51, 51, 255));
        txt_search.setBorder(null);
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 980, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusGained
        if (txt_name.getText().equals("Faculty Name")) {
            txt_name.setText("");
            txt_name.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_nameFocusGained

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost
        if (txt_name.getText().equals("")) {
            txt_name.setText("Faculty Name");
            txt_name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_nameFocusLost

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender="female";
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender="male";
    }//GEN-LAST:event_maleActionPerformed

    private void txt_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusGained
        if (txt_mail.getText().equals("Email")) {
            txt_mail.setText("");
            txt_mail.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_mailFocusGained

    private void txt_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusLost
        if (txt_mail.getText().equals("")) {
            txt_mail.setText("Email");
            txt_mail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_mailFocusLost

    private void txt_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusGained
        if (txt_address.getText().equals("Address")) {
            txt_address.setText("");
            txt_address.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_addressFocusGained

    private void txt_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusLost
        if (txt_address.getText().equals("")) {
            txt_address.setText("Address");
            txt_address.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_addressFocusLost

    private void txt_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusGained
        if (txt_phone.getText().equals("Contact Number")) {
            txt_phone.setText("");
            txt_phone.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_phoneFocusGained

    private void txt_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusLost
        if (txt_phone.getText().equals("")) {
            txt_phone.setText("Contact Number");
            txt_phone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_phoneFocusLost

    private void txt_qualificationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qualificationFocusGained
        if (txt_qualification.getText().equals("Qualification")) {
            txt_qualification.setText("");
            txt_qualification.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_qualificationFocusGained

    private void txt_qualificationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qualificationFocusLost
        if (txt_qualification.getText().equals("")) {
            txt_qualification.setText("Qualification");
            txt_qualification.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_qualificationFocusLost

    private void txt_experienceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_experienceFocusGained
        if (txt_experience.getText().equals("Experience")) {
            txt_experience.setText("");
            txt_experience.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_experienceFocusGained

    private void txt_experienceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_experienceFocusLost
        if (txt_experience.getText().equals("")) {
            txt_experience.setText("Experience");
            txt_experience.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_experienceFocusLost

    private void txt_experienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_experienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_experienceActionPerformed

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        if (txt_search.getText().equals("Enter Student Rollno")) {
            txt_search.setText("");
            txt_search.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
        if (txt_search.getText().equals("")) {
            txt_search.setText("Enter Student Rollno");
            txt_search.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_searchFocusLost

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            int id=Integer.parseInt(txt_search.getText());
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
                pst=con.prepareStatement("select * from faculty where id='"+id+"'");
                rs=pst.executeQuery();
                if(rs.next()){
                    txt_name.setText(rs.getString("facultyname"));
                    lbl_doa.setText(rs.getString("dob"));
                    lbl_doa.setText(rs.getString("dob"));
                    String gender=rs.getString("gender");
                    if(gender.equals("male")){
                        male.setSelected(true);
                    }else{
                        female.setSelected(true);
                    }
                    txt_mail.setText(rs.getString("email"));
                    txt_address.setText(rs.getString("address"));
                    txt_phone.setText(rs.getString("contact"));
                    byte[] path=rs.getBytes("pic");
                    ImageIcon icon=new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
                    lbl_image.setIcon(icon);
                    lbl_doj.setText(rs.getString("joiningdate"));
                    lbl_id.setText(rs.getString("id"));
                    lbl_position.setText(rs.getString("position"));
                    lbl_course.setText(rs.getString("course"));
                    lbl_subject.setText(rs.getString("subjectassign"));
                    lbl_sem.setText(rs.getString("semester"));
                    txt_qualification.setText(rs.getString("qualification"));
                    txt_experience.setText(rs.getString("experience"));
                }
                else
                JOptionPane.showMessageDialog(null, "Faculty Record Not Found!!!!");
               txt_search.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error in connection");
            }
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void back_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bttnActionPerformed
        faculty f=new faculty();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultydetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultydetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultydetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultydetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facultydetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_bttn;
    private javax.swing.JRadioButton female;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JTextField lbl_doa;
    private javax.swing.JTextField lbl_doj;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_position;
    private javax.swing.JLabel lbl_sem;
    private javax.swing.JLabel lbl_subject;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_experience;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_qualification;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
