/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculty;

import cms.Home;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author vaibhav
 */
public class faculty extends javax.swing.JFrame {

    /**
     * Creates new form faculty
     */
    public faculty() {
        initComponents();
         Connect();
         totalstudent();
    }
    /*************************************************************************************************************************/
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/cms", "root", "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(faculty.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(faculty.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 public void totalstudent(){
        Statement st;
     try {
            st=con.createStatement();
             rs=st.executeQuery("SELECT id FROM faculty");
            rs.last();
               jLabel10.setText(Integer.toString(rs.getRow()));
  
                    } catch (SQLException ex) {
            Logger.getLogger(faculty.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addfaculty = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        allrecord = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        totalfaculty = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        facultydetail = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Faculties");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 120));

        addfaculty.setBackground(new java.awt.Color(21, 25, 28));
        addfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfacultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addfacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addfacultyMouseExited(evt);
            }
        });
        addfaculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("Add Faculty");
        addfaculty.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facultylogin.png"))); // NOI18N
        addfaculty.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 100));

        jPanel1.add(addfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, 140));

        allrecord.setBackground(new java.awt.Color(21, 25, 28));
        allrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allrecordMouseExited(evt);
            }
        });
        allrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view report.png"))); // NOI18N
        allrecord.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setText("All Records");
        allrecord.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jPanel1.add(allrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 250, 190));

        home.setBackground(new java.awt.Color(21, 25, 28));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib icons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        home.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 60, 40));

        totalfaculty.setBackground(new java.awt.Color(21, 25, 28));
        totalfaculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(169, 224, 49));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view all record.png"))); // NOI18N
        totalfaculty.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("0");
        totalfaculty.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 30, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(169, 224, 49));
        jLabel11.setText("Total Faculties");
        totalfaculty.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel1.add(totalfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 180, 130));

        facultydetail.setBackground(new java.awt.Color(21, 25, 28));
        facultydetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultydetailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facultydetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facultydetailMouseExited(evt);
            }
        });
        facultydetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view all record.png"))); // NOI18N
        facultydetail.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel12.setText("Faculty Details");
        facultydetail.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel1.add(facultydetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 180, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void onclick(JPanel panel){
    panel.setBackground(new Color(0,153,204));
    }
    
    private void onleaveclick(JPanel panel){
    panel.setBackground(new Color(21,25,28));
    }
    public void setcolor(JPanel panel){
    panel.setBackground(new Color(153,153,153));
    }
    
    public void resetcolor(JPanel panel){
    panel.setBackground(new Color(21,25,28));
    }
    private void addfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseClicked
     onclick(addfaculty);
     onleaveclick(facultydetail);
     onleaveclick(allrecord);
    addfaculty af=new addfaculty();
    af.setVisible(true);
    dispose();
    }//GEN-LAST:event_addfacultyMouseClicked

    private void addfacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseEntered
        setcolor(addfaculty);
    }//GEN-LAST:event_addfacultyMouseEntered

    private void addfacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfacultyMouseExited
        resetcolor(addfaculty);
    }//GEN-LAST:event_addfacultyMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
      Home h=new Home();
      h.setVisible(true);
      dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        setcolor(home);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
       resetcolor(home);
    }//GEN-LAST:event_homeMouseExited

    private void facultydetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultydetailMouseClicked
        onleaveclick(addfaculty);
        onclick(facultydetail);
        onleaveclick(allrecord);
        facultydetail fd=new facultydetail();
        fd.setVisible(true);
        dispose();
    }//GEN-LAST:event_facultydetailMouseClicked

    private void facultydetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultydetailMouseEntered
        setcolor(facultydetail);
    }//GEN-LAST:event_facultydetailMouseEntered

    private void facultydetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultydetailMouseExited
         resetcolor(facultydetail);
    }//GEN-LAST:event_facultydetailMouseExited

    private void allrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allrecordMouseClicked
        onleaveclick(addfaculty);
        onleaveclick(facultydetail);
        onclick(allrecord);
        viewrecord a=new viewrecord();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_allrecordMouseClicked

    private void allrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allrecordMouseEntered
        setcolor(allrecord);
    }//GEN-LAST:event_allrecordMouseEntered

    private void allrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allrecordMouseExited
          resetcolor(allrecord);
    }//GEN-LAST:event_allrecordMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addfaculty;
    private javax.swing.JPanel allrecord;
    private javax.swing.JPanel facultydetail;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel totalfaculty;
    // End of variables declaration//GEN-END:variables
}
