/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.Message.RecipientType;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;



/**
 *
 * @author vaibhav
 */
public class forgetpass extends javax.swing.JFrame {
 int randomCode;

    /**
     * Creates new form forgetpass
     */
    public forgetpass() {
        initComponents();
        Connect();
        
    }
Connection con=null;
         PreparedStatement pst=null;
         ResultSet rs=null;
         
          public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/cms", "root", "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(forgetpass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(forgetpass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgetpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        minimize_bttn = new javax.swing.JButton();
        txtcode = new javax.swing.JTextField();
        verifybttn = new javax.swing.JButton();
        sendbttn = new javax.swing.JButton();
        txt_mail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgetpanel.setBackground(new java.awt.Color(21, 25, 28));
        forgetpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pic.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 110, 660, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Forget Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_reed.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 40));

        minimize_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        minimize_bttn.setToolTipText("Minimize");
        minimize_bttn.setBorder(null);
        minimize_bttn.setBorderPainted(false);
        minimize_bttn.setContentAreaFilled(false);
        minimize_bttn.setFocusPainted(false);
        minimize_bttn.setRequestFocusEnabled(false);
        minimize_bttn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus_red.png"))); // NOI18N
        minimize_bttn.setVerifyInputWhenFocusTarget(false);
        minimize_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_bttnMouseClicked(evt);
            }
        });
        minimize_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(minimize_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 40));

        forgetpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 400, 470));

        txtcode.setBackground(new java.awt.Color(31, 36, 42));
        txtcode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtcode.setForeground(new java.awt.Color(153, 153, 153));
        txtcode.setText("Verify Code");
        txtcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcodeFocusLost(evt);
            }
        });
        forgetpanel.add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 280, 40));

        verifybttn.setBackground(new java.awt.Color(152, 201, 45));
        verifybttn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        verifybttn.setForeground(new java.awt.Color(21, 25, 28));
        verifybttn.setText("Verify");
        verifybttn.setBorder(null);
        verifybttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verifybttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifybttnActionPerformed(evt);
            }
        });
        forgetpanel.add(verifybttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 90, -1));

        sendbttn.setBackground(new java.awt.Color(152, 201, 45));
        sendbttn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sendbttn.setForeground(new java.awt.Color(21, 25, 28));
        sendbttn.setText("Send");
        sendbttn.setBorder(null);
        sendbttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbttnActionPerformed(evt);
            }
        });
        forgetpanel.add(sendbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 90, -1));

        txt_mail.setBackground(new java.awt.Color(31, 36, 42));
        txt_mail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(153, 153, 153));
        txt_mail.setText("Enter Email");
        txt_mail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mailFocusLost(evt);
            }
        });
        forgetpanel.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 40));

        getContentPane().add(forgetpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcodeFocusGained
        if (txtcode.getText().equals("Verify Code")) {
            txtcode.setText("");
            txtcode.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txtcodeFocusGained

    private void txtcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcodeFocusLost
       if (txtcode.getText().equals("")) {
            txtcode.setText("Verify Code");
            txtcode.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtcodeFocusLost

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void minimize_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_bttnMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimize_bttnMouseClicked

    private void minimize_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_bttnActionPerformed

    }//GEN-LAST:event_minimize_bttnActionPerformed

    private void sendbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbttnActionPerformed
       try{
	Random	ran=new Random();
        randomCode=ran.nextInt(999999);
        String host = "smtp.gmail.com";
        String user ="noreply.kamalinstitute@gmail.com";
        String pass="kamalkiheat";
        String to = txt_mail.getText();
        String subject="Password Reseting Code";
        String message ="Hi,we received a request to change the password. Use " +randomCode+ " to reset your password."
                + "This email has been automatically generated."
                + "Please do no reply.";  
        Properties pros = System.getProperties();
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.host", "host");
        pros.put("mail.smtp.port","465");
        pros.put("mail.smtp.auth","true");
        pros.put("mail.smtp.debug","true");
        pros.put("mail.smtp.socketFactory.port","465");
        pros.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(pros, null);
        mailSession.setDebug(true);
        MimeMessage msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(user));
        msg.addRecipient(RecipientType.TO, new InternetAddress(to));
        msg.setSubject(subject);
       msg.setText(message);
       Transport transport = mailSession.getTransport("smtp");
      transport.connect(host, user, pass);
      transport.sendMessage(msg, msg.getAllRecipients());
      transport.close();
      JOptionPane.showMessageDialog(null, "code has been send to the email");
      }catch(Exception ex){
      JOptionPane.showMessageDialog(rootPane, ex);
       }	
        	
    }//GEN-LAST:event_sendbttnActionPerformed

    private void txt_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusGained
       if(txt_mail.getText().equals("Enter Email")){
          txt_mail.setText("");
          txt_mail.setForeground(new Color(255,255,255));
       }
    }//GEN-LAST:event_txt_mailFocusGained

    private void txt_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusLost
         if(txt_mail.getText().equals("")){
          txt_mail.setText("Enter Email");
          txt_mail.setForeground(new Color(153,153,153));
       }
    }//GEN-LAST:event_txt_mailFocusLost

    private void verifybttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifybttnActionPerformed
        if(Integer.valueOf(txtcode.getText())==randomCode){
          resetpass r=new resetpass(txt_mail.getText());
          r.setVisible(true);
          this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Please Enter the correct code!!");
        }
    }//GEN-LAST:event_verifybttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel forgetpanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton minimize_bttn;
    private javax.swing.JButton sendbttn;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txtcode;
    private javax.swing.JButton verifybttn;
    // End of variables declaration//GEN-END:variables
}
