/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import cms.cource.cource;
import cms.fee.fees_menu;
import cms.library.library;
import cms.student.studentform;
import faculty.faculty;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import subject.subject;
/**
 *
 * @author vaibhav
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
        Connect();
        
    }
    int iid;
    String username;
    String usertype;
    
    public Home(int id, String username, String usertype) {
         initComponents();
         this.username=username;
         lbl_name.setText(username);
         
         this.usertype=usertype;
         lbl_type.setText(usertype);
         
         this.iid=id;
    }
    
    Connection con;
         PreparedStatement pst;
         ResultSet rs;
          DefaultTableModel d;
          
           public void Connect()
            {
              try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3307/college_management" , "root" , "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
   
/*********************************************************************************************************************************/
          
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        cource = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subject = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        student = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        faculty = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_type = new javax.swing.JLabel();
        library = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fee = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(21, 25, 28));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        logo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("Kamal Institute Of Higher Education And Advanced Technology");
        logo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_reed.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        logo.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        menu.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 160));

        cource.setBackground(new java.awt.Color(21, 25, 28));
        cource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courceMouseExited(evt);
            }
        });
        cource.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("Cources");
        cource.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courceshomepage.png"))); // NOI18N
        cource.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 90));

        menu.add(cource, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 150, 140));

        subject.setBackground(new java.awt.Color(21, 25, 28));
        subject.setForeground(new java.awt.Color(21, 25, 28));
        subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subjectMouseExited(evt);
            }
        });
        subject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(21, 25, 28));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 25, 28));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subjects2.png"))); // NOI18N
        subject.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 90));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setText("Subject");
        subject.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        menu.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 150, 140));

        student.setBackground(new java.awt.Color(21, 25, 28));
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentMouseExited(evt);
            }
        });
        student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentlogin.png"))); // NOI18N
        student.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 90));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("Students");
        student.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        menu.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, 140));

        faculty.setBackground(new java.awt.Color(21, 25, 28));
        faculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facultyMouseExited(evt);
            }
        });
        faculty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(169, 224, 49));
        jLabel10.setText("Faculties");
        faculty.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facultylogin.png"))); // NOI18N
        faculty.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 90));

        menu.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 150, 140));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(51, 51, 255));
        menu.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 120, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Logged in as");
        menu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Welcome");
        menu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        lbl_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_type.setForeground(new java.awt.Color(51, 51, 255));
        menu.add(lbl_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 90, 30));

        library.setBackground(new java.awt.Color(21, 25, 28));
        library.setForeground(new java.awt.Color(21, 25, 28));
        library.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libraryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libraryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libraryMouseExited(evt);
            }
        });
        library.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(21, 25, 28));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 25, 28));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/text-book-opened-from-top-view.png"))); // NOI18N
        library.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 100));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 224, 49));
        jLabel13.setText("Library");
        library.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        menu.add(library, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 150, 140));

        fee.setBackground(new java.awt.Color(21, 25, 28));
        fee.setForeground(new java.awt.Color(21, 25, 28));
        fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feeMouseExited(evt);
            }
        });
        fee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(21, 25, 28));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(21, 25, 28));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib icons/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        fee.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 90));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel16.setText("Fee");
        fee.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        menu.add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 150, 140));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void set(JPanel panel){
    panel.setBackground(new Color(153,153,153));
    }
    
    private void reset(JPanel panel){
    panel.setBackground(new Color(21,25,28));
    }
   
    private void subjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectMouseEntered
         set(subject);
    }//GEN-LAST:event_subjectMouseEntered

    private void subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectMouseClicked
        subject s=new subject();
        s.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_subjectMouseClicked

    private void studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseClicked

        studentform sf=new studentform();
        sf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentMouseClicked

    private void facultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyMouseClicked
        faculty f=new faculty();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_facultyMouseClicked

    private void courceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courceMouseClicked

        cource c=new cource();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_courceMouseClicked

    private void studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseEntered
    set(student);
    }//GEN-LAST:event_studentMouseEntered

    private void studentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseExited
       reset(student);
    }//GEN-LAST:event_studentMouseExited

    private void facultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyMouseEntered
       set(faculty);
    }//GEN-LAST:event_facultyMouseEntered

    private void facultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyMouseExited
       reset(faculty);
    }//GEN-LAST:event_facultyMouseExited

    private void subjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectMouseExited
      reset(subject);
    }//GEN-LAST:event_subjectMouseExited

    private void courceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courceMouseEntered
       set(cource);
    }//GEN-LAST:event_courceMouseEntered

    private void courceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courceMouseExited
       reset(cource);
    }//GEN-LAST:event_courceMouseExited

    private void libraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryMouseClicked
        
        library l=new library();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_libraryMouseClicked

    private void libraryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryMouseEntered
       set(library);
    }//GEN-LAST:event_libraryMouseEntered

    private void libraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryMouseExited
      reset(library);
    }//GEN-LAST:event_libraryMouseExited

    private void feeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeMouseClicked
       fees_menu fm=new fees_menu();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_feeMouseClicked

    private void feeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeMouseEntered
        set(fee);
    }//GEN-LAST:event_feeMouseEntered

    private void feeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeMouseExited
        reset(fee);
    }//GEN-LAST:event_feeMouseExited

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cource;
    private javax.swing.JPanel faculty;
    private javax.swing.JPanel fee;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JPanel library;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel student;
    private javax.swing.JPanel subject;
    // End of variables declaration//GEN-END:variables

}
