/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import cms.login.LoginForm;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class resetpass extends javax.swing.JFrame {
    Connection con=null;
         PreparedStatement pst=null;
         ResultSet rs=null;
    public String mail;
    /**
     * Creates new form resetpass
     */
    public resetpass() {
        initComponents();
        
    }
    public resetpass(String email){
      this.mail=email;
       initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minimize_bttn = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        txt_newpass = new javax.swing.JTextField();
        txt_conpass = new javax.swing.JTextField();
        resetbttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 420));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Reset Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        minimize_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        minimize_bttn.setToolTipText("Minimize");
        minimize_bttn.setBorder(null);
        minimize_bttn.setBorderPainted(false);
        minimize_bttn.setContentAreaFilled(false);
        minimize_bttn.setFocusPainted(false);
        minimize_bttn.setRequestFocusEnabled(false);
        minimize_bttn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus_red.png"))); // NOI18N
        minimize_bttn.setVerifyInputWhenFocusTarget(false);
        minimize_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_bttnMouseClicked(evt);
            }
        });
        minimize_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(minimize_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_reed.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 510, 480));

        txt_newpass.setBackground(new java.awt.Color(31, 36, 42));
        txt_newpass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_newpass.setForeground(new java.awt.Color(153, 153, 153));
        txt_newpass.setText("Enter New Password");
        txt_newpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_newpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_newpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_newpassFocusLost(evt);
            }
        });
        jPanel1.add(txt_newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 40));

        txt_conpass.setBackground(new java.awt.Color(31, 36, 42));
        txt_conpass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_conpass.setForeground(new java.awt.Color(153, 153, 153));
        txt_conpass.setText("Confirm New Password");
        txt_conpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_conpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_conpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_conpassFocusLost(evt);
            }
        });
        txt_conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conpassActionPerformed(evt);
            }
        });
        jPanel1.add(txt_conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, 40));

        resetbttn.setBackground(new java.awt.Color(152, 201, 45));
        resetbttn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetbttn.setForeground(new java.awt.Color(21, 25, 28));
        resetbttn.setText("Reset Password");
        resetbttn.setBorder(null);
        resetbttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbttnActionPerformed(evt);
            }
        });
        jPanel1.add(resetbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       
           
    private void txt_newpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_newpassFocusGained
        if (txt_newpass.getText().equals("Enter New Password")) {
            txt_newpass.setText("");
            txt_newpass.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txt_newpassFocusGained

    private void txt_newpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_newpassFocusLost
        if (txt_newpass.getText().equals("")) {
            txt_newpass.setText("Enter New Password");
            txt_newpass.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_newpassFocusLost

    private void txt_conpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_conpassFocusGained
        if (txt_conpass.getText().equals("Confirm New Password")) {
            txt_conpass.setText("");
            txt_conpass.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txt_conpassFocusGained

    private void txt_conpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_conpassFocusLost
        if (txt_conpass.getText().equals("")) {
            txt_conpass.setText("Confirm New Password");
            txt_conpass.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_conpassFocusLost

    private void txt_conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_conpassActionPerformed

    private void resetbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbttnActionPerformed
        if(txt_newpass.getText().equals(txt_conpass.getText())){ //check whether user enter same password in both the fields
            try{
                String updateQuery ="UPDATE signin SET password=? WHERE email=?";
                con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
                pst=con.prepareStatement(updateQuery);
                pst.setString(1, txt_conpass.getText());
                pst.setString(2, mail);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Password Reset Successfully!!");
            LoginForm lf=new LoginForm();
            lf.setVisible(true);
            dispose();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Password do not match");
        }
    }//GEN-LAST:event_resetbttnActionPerformed

    private void minimize_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_bttnMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimize_bttnMouseClicked

    private void minimize_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_bttnActionPerformed

    }//GEN-LAST:event_minimize_bttnActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton minimize_bttn;
    private javax.swing.JButton resetbttn;
    private javax.swing.JTextField txt_conpass;
    private javax.swing.JTextField txt_newpass;
    // End of variables declaration//GEN-END:variables
}
