/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subject;

import faculty.facultydetail;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class assignsubject extends javax.swing.JFrame {
BufferedImage buf=null;
    /**
     * Creates new form assignsubject
     */
    public assignsubject() {
        initComponents();
        Connect();
        updatecourse();
        updatesubject();
    }
 
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/cms", "root", "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(facultydetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(facultydetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**************************************************************************************/
    
    /************************************************************************************/
    public void updatecourse(){
    try {
            pst=con.prepareStatement("SELECT * FROM cource");
            rs=pst.executeQuery();
            while(rs.next()){
               course_combo.addItem(rs.getString("courcename"));
             
            }  
        } catch (SQLException ex) {
            Logger.getLogger(assignsubject.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /************************************************************************************/
    public void updatesubject(){
    try {
            pst=con.prepareStatement("SELECT * FROM subject");
            rs=pst.executeQuery();
            while(rs.next()){
               sub_combo.addItem(rs.getString("subjectname"));
             
            }  
        } catch (SQLException ex) {
            Logger.getLogger(assignsubject.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        back_bttn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_image = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_exp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_qual = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        sem_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        course_combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        sub_combo = new javax.swing.JComboBox<>();
        assign_bttn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lbl_position = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assign Subject");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_reed.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 40));

        back_bttn.setBackground(new java.awt.Color(0, 153, 102));
        back_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_bttnMouseClicked(evt);
            }
        });
        back_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_bttn.png"))); // NOI18N
        jLabel3.setText("Back");
        back_bttn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel2.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 80));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopPane1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 180));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 200));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Experience");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Faculty Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        lbl_exp.setBackground(new java.awt.Color(31, 36, 42));
        lbl_exp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_exp.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qualification");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        lbl_name.setBackground(new java.awt.Color(31, 36, 42));
        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 220, 30));

        lbl_qual.setBackground(new java.awt.Color(31, 36, 42));
        lbl_qual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_qual.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_qual, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 220, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 920, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Faculty Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        sem_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Select Semester--------", "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6 " }));
        jPanel1.add(sem_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 240, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        course_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Select Course--------" }));
        jPanel1.add(course_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 240, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        sub_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select Subject---------" }));
        jPanel1.add(sub_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 240, 30));

        assign_bttn.setBackground(new java.awt.Color(152, 201, 45));
        assign_bttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assign_bttn.setText("Assign Subject");
        assign_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assign_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assign_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(assign_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 130, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Position");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        lbl_position.setBackground(new java.awt.Color(31, 36, 42));
        lbl_position.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_position.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 210, 30));

        txt_search.setBackground(new java.awt.Color(21, 25, 28));
        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_search.setForeground(new java.awt.Color(51, 51, 255));
        txt_search.setBorder(null);
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 180, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void assign_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_bttnActionPerformed
       
        String course=course_combo.getSelectedItem().toString();
          String semester=sem_combo.getSelectedItem().toString();
           String subjectassign=sub_combo.getSelectedItem().toString();
             try {
                 pst=con.prepareStatement("update faculty set course='"+course_combo.getSelectedItem().toString()+"'"
                         + ",semester='"+sem_combo.getSelectedItem().toString()+"',"
                                 + "subjectassign='"+sub_combo.getSelectedItem().toString()+"';");
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Subject Assigned Successfully !!!");
                 facultydetail fd=new facultydetail();
                 fd.setVisible(true);
                  dispose();
             } catch (SQLException ex) {
                 Logger.getLogger(assignsubject.class.getName()).log(Level.SEVERE, null, ex);
             }
           
    }//GEN-LAST:event_assign_bttnActionPerformed

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        if (txt_search.getText().equals("Enter Student Rollno")) {
            txt_search.setText("");
            txt_search.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
        if (txt_search.getText().equals("")) {
            txt_search.setText("Enter Student Rollno");
            txt_search.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_searchFocusLost

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            int id=Integer.parseInt(txt_search.getText());
            try {
                pst=con.prepareStatement("select * from faculty where id='"+id+"'");
                rs=pst.executeQuery();
                if(rs.next()){
                    lbl_name.setText(rs.getString("facultyname"));
                    lbl_position.setText(rs.getString("position"));
                    lbl_qual.setText(rs.getString("qualification"));
                    byte[] path=rs.getBytes("pic");
                    ImageIcon icon=new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
                    lbl_image.setIcon(icon);
                    lbl_exp.setText(rs.getString("experience"));
                }
                else
                JOptionPane.showMessageDialog(null, "Faculty  Not Found!!!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error in connection");
            }
        }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void back_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseClicked
        
    }//GEN-LAST:event_back_bttnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignsubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assign_bttn;
    private javax.swing.JPanel back_bttn;
    private javax.swing.JComboBox<String> course_combo;
    private javax.swing.JButton jButton10;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_exp;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_position;
    private javax.swing.JLabel lbl_qual;
    private javax.swing.JComboBox<String> sem_combo;
    private javax.swing.JComboBox<String> sub_combo;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
