/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.cource;

import cms.Home;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author vaibhav
 */
public class cource extends javax.swing.JFrame {

    /**
     * Creates new form cource
     */
    public cource() {
        initComponents();
        Connect();
        updatetable();
    }
    
     Connection con;
            PreparedStatement pst;
            ResultSet rs;
            DefaultTableModel d;
            
            public void Connect()
            {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(cource.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(cource.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
     /**********************************************************************************************************/
             public void updatetable(){
      try{
         pst=con.prepareStatement("SELECT * from cource");
             rs=pst.executeQuery();
             while(rs.next()){
                 String courceid=rs.getString("id");
                 String courcename=rs.getString("courcename");
                 String courcecost=rs.getString("courcecost");
                Object[] obj={courceid,courcename,courcecost};
                d=(DefaultTableModel)table_cource.getModel();
                d.addRow(obj);
             }
      }catch(Exception e){
      
      }
    }
/***************************************************************************************************************/
             public void cleartable(){
              d=(DefaultTableModel)table_cource.getModel();
              d.setRowCount(0);
             }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_ccost = new javax.swing.JTextField();
        lbl_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_cname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_cource = new rojeru_san.complementos.RSTableMetro();
        add = new rojerusan.RSMaterialButtonCircle();
        delete = new rojerusan.RSMaterialButtonCircle();
        update = new rojerusan.RSMaterialButtonCircle();
        back_bttn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Cource");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cource Cost :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cource Id :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lbl_ccost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ccost.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_ccost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 210, 40));

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cource Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lbl_cname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cname.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 210, 40));

        table_cource.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cource Name", "Cource Cost"
            }
        ));
        table_cource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_courceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_cource);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 52, 470, 460));

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 70));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 240, 70));

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 200, 60));

        back_bttn.setBackground(new java.awt.Color(21, 25, 28));
        back_bttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_bttnMouseClicked(evt);
            }
        });
        back_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_bttn.png"))); // NOI18N
        jLabel17.setText("Back");
        back_bttn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel1.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_reed.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_courceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_courceMouseClicked
        int r= table_cource.getSelectedRow();
       TableModel tm=table_cource.getModel();
       lbl_id.setText(tm.getValueAt(r, 0).toString());
       lbl_cname.setText(tm.getValueAt(r,1).toString());
       lbl_ccost.setText(tm.getValueAt(r,2).toString());
    }//GEN-LAST:event_table_courceMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int id=Integer.parseInt(lbl_id.getText());
        String courcename=lbl_cname.getText();
        double courcecost=Double.parseDouble(lbl_ccost.getText());
        try{
            pst=con.prepareStatement("insert into cource values(?,?,?)");
            pst.setInt(1, id);
            pst.setString(2, courcename);
            pst.setDouble(3, courcecost);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Cource Added Successfully!!");
            cleartable();
            lbl_id.setText("");
            lbl_cname.setText("");
            lbl_ccost.setText("");
            lbl_id.requestFocus();
        }catch (SQLException ex) {
            Logger.getLogger(cource.class.getName()).log(Level.SEVERE, null, ex);
        }
        updatetable();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int id=Integer.parseInt(lbl_id.getText());
       try {
            pst= con.prepareStatement("delete from cource  where id=?");
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Cource Deleted Successfully!!");
            cleartable();
          lbl_id.setText("");
            lbl_cname.setText("");
            lbl_ccost.setText("");
            lbl_id.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(cource.class.getName()).log(Level.SEVERE, null, ex);
        }
updatetable();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int id=Integer.parseInt(lbl_id.getText());
        String courcename= lbl_cname.getText();
        double courcecost= Double.parseDouble(lbl_ccost.getText());

        try {
            pst= con.prepareStatement("update cource set courcename=? , courcecost=?  where id=?");
            pst.setString(1,courcename);
            pst.setDouble(2,courcecost);
            pst.setInt(3, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Cource Edited Successfully!!");
            cleartable();

        } catch (SQLException ex) {
            Logger.getLogger(cource.class.getName()).log(Level.SEVERE, null, ex);
        }
updatetable();
    }//GEN-LAST:event_updateActionPerformed

    private void back_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseClicked
        Home h=new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_bttnMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle add;
    private javax.swing.JPanel back_bttn;
    private rojerusan.RSMaterialButtonCircle delete;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lbl_ccost;
    private javax.swing.JTextField lbl_cname;
    private javax.swing.JTextField lbl_id;
    private rojeru_san.complementos.RSTableMetro table_cource;
    private rojerusan.RSMaterialButtonCircle update;
    // End of variables declaration//GEN-END:variables
}
