/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.fee;

import cms.Home;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author vaibhav
 */
public class fees_menu extends javax.swing.JFrame {

    /**
     * Creates new form fees_menu
     */
    public fees_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        search_record = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addfee = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewrecord = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        report = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(21, 25, 28));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        logo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("Advanced Technology");
        logo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 310, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Kamal Institute Of Higher Education ");
        logo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 440, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("And");
        logo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 60, 30));

        home.setBackground(new java.awt.Color(21, 25, 28));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib icons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        home.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        logo.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 60, 40));

        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 160));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_record.setBackground(new java.awt.Color(21, 25, 28));
        search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_recordMouseExited(evt);
            }
        });
        search_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/search-document.png"))); // NOI18N
        search_record.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel5.setBackground(new java.awt.Color(0, 204, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("Search Records");
        search_record.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel1.add(search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 150, 190));

        addfee.setBackground(new java.awt.Color(21, 25, 28));
        addfee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addfeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addfeeMouseExited(evt);
            }
        });
        addfee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/plus.png"))); // NOI18N
        addfee.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel10.setBackground(new java.awt.Color(0, 204, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("Add Fees");
        addfee.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jPanel1.add(addfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 190));

        viewrecord.setBackground(new java.awt.Color(21, 25, 28));
        viewrecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewrecord.setMinimumSize(new java.awt.Dimension(140, 175));
        viewrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecordMouseExited(evt);
            }
        });
        viewrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/text-book-opened-from-top-view.png"))); // NOI18N
        viewrecord.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 130));

        jLabel12.setBackground(new java.awt.Color(0, 204, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("View Records");
        viewrecord.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanel1.add(viewrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, 190));

        report.setBackground(new java.awt.Color(21, 25, 28));
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportMouseExited(evt);
            }
        });
        report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view report.png"))); // NOI18N
        report.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 140));

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("View Report");
        report.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 150, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 840, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void setcolor(JPanel panel){
    panel.setBackground(new Color(153,153,153));
    }
    
    public void resetcolor(JPanel panel){
    panel.setBackground(new Color(21,25,28));
    }
    private void search_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_recordMouseEntered
       setcolor(search_record);
    }//GEN-LAST:event_search_recordMouseEntered

    private void addfeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfeeMouseEntered
        setcolor(addfee);
        
    }//GEN-LAST:event_addfeeMouseEntered

    private void search_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_recordMouseExited
        resetcolor(search_record);
    }//GEN-LAST:event_search_recordMouseExited

    private void addfeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfeeMouseExited
        resetcolor(addfee);
    }//GEN-LAST:event_addfeeMouseExited

    private void viewrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordMouseEntered
        setcolor(viewrecord);
    }//GEN-LAST:event_viewrecordMouseEntered

    private void viewrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordMouseExited
       resetcolor(viewrecord);
    }//GEN-LAST:event_viewrecordMouseExited

    private void addfeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfeeMouseClicked
       addfee af=new addfee();
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addfeeMouseClicked

    private void search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_recordMouseClicked
       search_fee_records sf=new search_fee_records();
       sf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_search_recordMouseClicked

    private void viewrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecordMouseClicked
        viewrecords vr=new viewrecords();
        vr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewrecordMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
       report vr=new report();
       vr.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_reportMouseClicked

    private void reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseEntered
       setcolor(report);
    }//GEN-LAST:event_reportMouseEntered

    private void reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseExited
        resetcolor(report);
    }//GEN-LAST:event_reportMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Home h=new Home();
         h.setVisible(true);
         dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        setcolor(home);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        resetcolor(home);
    }//GEN-LAST:event_homeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addfee;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel report;
    private javax.swing.JPanel search_record;
    private javax.swing.JPanel viewrecord;
    // End of variables declaration//GEN-END:variables
}
