/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.fee;

import cms.Home;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author vaibhav
 */
public class printreceipt extends javax.swing.JFrame {

    /**
     * Creates new form printreceipt
     */
    public printreceipt() {
        initComponents();
        Connect();
        showrecords();
    }
    
    
    Connection con;
         PreparedStatement pst;
         ResultSet rs;
       
           public void Connect()
            {
              try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addfee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addfee.class.getName()).log(Level.SEVERE, null, ex);
        } 
            }
/****************************************************************************************************************************/
    public void showrecords(){
     try {
            pst=con.prepareStatement("SELECT * from fees order by receipt_no desc limit 1"); /*fetch the records in descending order*/
             rs=pst.executeQuery();
             rs.next();
             txt_receiptno.setText(rs.getString("receipt_no"));
             txt_receivedfrom.setText(rs.getString("student_name"));
             txt_paymentmode.setText(rs.getString("payment_mode"));
             String payment_mode=rs.getString("payment_mode");
             
             if(payment_mode.equalsIgnoreCase("Cash")){
                 lbl_cheque.setText("cheque_no");
                 txt_cheque_dd.setText("-");
                 txt_bankname.setText("-");
             }
             if(payment_mode.equalsIgnoreCase("Cheque")){
                 lbl_cheque.setText("cheque_no");
                 txt_cheque_dd.setText(rs.getString("cheque_no"));
                 txt_bankname.setText(rs.getString("bank_name"));
             }
             
             if(payment_mode.equalsIgnoreCase("Demand Draft")){
                 lbl_cheque.setText("dd_no");
                 txt_cheque_dd.setText(rs.getString("dd_no"));
                 txt_bankname.setText(rs.getString("bank_name"));
             }
             
             if(payment_mode.equalsIgnoreCase("Card")){
                 lbl_cheque.setText("-");
                 txt_cheque_dd.setText("-");
                 txt_bankname.setText(rs.getString("bank_name"));
             }
             
             txt_gstin.setText(rs.getString("gstin"));
             txt_semester.setText(rs.getString("semester"));
             txt_year1.setText(rs.getString("year1"));
             txt_year2.setText(rs.getString("year2"));
             txt_coursename.setText(rs.getString("course_name"));
             txt_amount.setText(rs.getString("amount"));
             txt_cgstamount.setText(rs.getString("cgst"));
             txt_sgstamount.setText(rs.getString("sgst"));
             txt_total.setText(rs.getString("total_amount"));
             txt_amountword.setText(rs.getString("total_amount_word"));
             txt_date.setText(rs.getString("date"));
                    } catch (SQLException ex) {
            Logger.getLogger(addfee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        home_bttn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search_bttn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        print_option = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        edit_bttn = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        viewrecord_bttn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        back_bttn = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        logout_bttn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_receiptno = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_cheque = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        txt_receivedfrom = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        txt_coursename = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_coursename1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_sgstamount = new javax.swing.JLabel();
        txt_amount = new javax.swing.JLabel();
        txt_cgstamount = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_total = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_amountword = new javax.swing.JLabel();
        txt_semester = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 102, 51));
        sidebar.setForeground(new java.awt.Color(0, 204, 51));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_bttn.setBackground(new java.awt.Color(0, 102, 51));
        home_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_bttnMouseExited(evt);
            }
        });
        home_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        home_bttn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");
        home_bttn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 40));

        sidebar.add(home_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 70));

        search_bttn.setBackground(new java.awt.Color(0, 102, 51));
        search_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        search_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_bttnMouseExited(evt);
            }
        });
        search_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/search2.png"))); // NOI18N
        search_bttn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search Record");
        search_bttn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 30));

        sidebar.add(search_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 70));

        print_option.setBackground(new java.awt.Color(0, 102, 51));
        print_option.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print_option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_optionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_optionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print_optionMouseExited(evt);
            }
        });
        print_option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/printer-.png"))); // NOI18N
        jLabel32.setText("Print");
        print_option.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 70));

        sidebar.add(print_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 70));

        edit_bttn.setBackground(new java.awt.Color(0, 102, 51));
        edit_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_bttnMouseExited(evt);
            }
        });
        edit_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit2.png"))); // NOI18N
        jLabel29.setText("Edit");
        edit_bttn.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, -1));

        sidebar.add(edit_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, 70));

        viewrecord_bttn.setBackground(new java.awt.Color(0, 102, 51));
        viewrecord_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewrecord_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        viewrecord_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseExited(evt);
            }
        });
        viewrecord_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/list_1.png"))); // NOI18N
        viewrecord_bttn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("View Record");
        viewrecord_bttn.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(viewrecord_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 190, 70));

        back_bttn.setBackground(new java.awt.Color(0, 102, 51));
        back_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        back_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_bttnMouseExited(evt);
            }
        });
        back_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/left-arrow.png"))); // NOI18N
        back_bttn.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Back");
        back_bttn.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 190, 70));

        logout_bttn.setBackground(new java.awt.Color(0, 102, 51));
        logout_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        logout_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_bttnMouseExited(evt);
            }
        });
        logout_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        logout_bttn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Logout");
        logout_bttn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(logout_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 190, 70));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Advanced Technology");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("And ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Kamal Institute Of Higher Education ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("K1 Extn. Mohan Garden, Near Nawada Metro Station, New Delhi");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 770, 6));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Reciept No : ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txt_receiptno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_receiptno.setForeground(new java.awt.Color(255, 51, 51));
        txt_receiptno.setText("receiptno");
        jPanel3.add(txt_receiptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 100, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("KIHEAT -");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("GSTIN :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("The Following Payment in the college for the year");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lbl_cheque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cheque.setText("Cheque_DD :");
        jPanel3.add(lbl_cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Payment Mode :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lbl_bankname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bankname.setText("Bank Name :");
        jPanel3.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Received From :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        txt_paymentmode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_paymentmode.setForeground(new java.awt.Color(255, 51, 51));
        txt_paymentmode.setText("payment mode");
        jPanel3.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, 30));

        txt_cheque_dd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_cheque_dd.setText("cheque_dd");
        jPanel3.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, 30));

        txt_bankname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_bankname.setText("bank name");
        jPanel3.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, 30));

        txt_receivedfrom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_receivedfrom.setForeground(new java.awt.Color(0, 0, 255));
        txt_receivedfrom.setText("received from");
        jPanel3.add(txt_receivedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, 40));

        txt_year2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_year2.setForeground(new java.awt.Color(0, 153, 51));
        txt_year2.setText("year2");
        jPanel3.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 70, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("-");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        txt_year1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_year1.setForeground(new java.awt.Color(0, 153, 51));
        txt_year1.setText("year1");
        jPanel3.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 70, 30));

        txt_gstin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_gstin.setForeground(new java.awt.Color(153, 0, 153));
        jPanel3.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 120, 30));

        txt_coursename.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_coursename.setText("coursename");
        jPanel3.add(txt_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 110, 30));

        txt_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 120, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 770, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 770, 10));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Date :");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Sr.no");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Head");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_sgst.setText("sgst 9%");
        jPanel3.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("1");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        txt_coursename1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(txt_coursename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 150, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Amount(rs)");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_cgst.setText("cgst 9%");
        jPanel3.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        txt_sgstamount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_sgstamount.setForeground(new java.awt.Color(255, 0, 0));
        txt_sgstamount.setText("sgst");
        jPanel3.add(txt_sgstamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 110, 30));

        txt_amount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_amount.setForeground(new java.awt.Color(255, 0, 0));
        txt_amount.setText("amount");
        jPanel3.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 110, 20));

        txt_cgstamount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_cgstamount.setForeground(new java.awt.Color(255, 0, 0));
        txt_cgstamount.setText("cgst");
        jPanel3.add(txt_cgstamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 110, 30));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 240, -1));

        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(153, 0, 0));
        txt_total.setText("total amount");
        jPanel3.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 120, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Total in words: ");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 140, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("This is a computer generated DUPLICATE INVOICE and requires no signature.");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 670, 30));

        txt_amountword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_amountword.setForeground(new java.awt.Color(51, 153, 0));
        txt_amountword.setText("amount in words");
        jPanel3.add(txt_amountword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 450, 40));

        txt_semester.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_semester.setText("semester");
        jPanel3.add(txt_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 0, 770, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseClicked
        fees_menu fm=new fees_menu();
        fm.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_bttnMouseClicked

    private void home_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseEntered
        set(home_bttn);

    }//GEN-LAST:event_home_bttnMouseEntered

    private void home_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseExited
        reset(home_bttn);
    }//GEN-LAST:event_home_bttnMouseExited

    private void search_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bttnMouseClicked
        search_fee_records sfr=new search_fee_records();
        sfr.setVisible(true);
        dispose();
    }//GEN-LAST:event_search_bttnMouseClicked

    private void search_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bttnMouseEntered
        set(search_bttn);
    }//GEN-LAST:event_search_bttnMouseEntered

    private void search_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bttnMouseExited
        reset(search_bttn);
    }//GEN-LAST:event_search_bttnMouseExited

    private void print_optionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseClicked
       PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable(){                    /*anonymus inner class*/
            public int print(Graphics pg,PageFormat pf, int pageNum){     /*one-time use only*/
                pf.setOrientation(PageFormat.PORTRAIT);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);

                jPanel3.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if(ok){
            try{

                job.print();
            }
            catch (PrinterException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_print_optionMouseClicked

    private void print_optionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseEntered
        set(print_option);
    }//GEN-LAST:event_print_optionMouseEntered

    private void print_optionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseExited
        reset(print_option);
    }//GEN-LAST:event_print_optionMouseExited

    private void edit_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseClicked
        editreceipt er=new editreceipt();
        er.setVisible(true);
        dispose();
    }//GEN-LAST:event_edit_bttnMouseClicked

    private void edit_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseEntered
        set(edit_bttn);
    }//GEN-LAST:event_edit_bttnMouseEntered

    private void edit_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseExited
        reset(edit_bttn);
    }//GEN-LAST:event_edit_bttnMouseExited

    private void viewrecord_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseClicked
        viewrecords vr=new viewrecords();
        vr.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewrecord_bttnMouseClicked

    private void viewrecord_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseEntered
        set(viewrecord_bttn);
    }//GEN-LAST:event_viewrecord_bttnMouseEntered

    private void viewrecord_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseExited
        reset(viewrecord_bttn);
    }//GEN-LAST:event_viewrecord_bttnMouseExited

    private void back_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseClicked
        fees_menu f=new fees_menu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_bttnMouseClicked

    private void back_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseEntered
        set(back_bttn);
    }//GEN-LAST:event_back_bttnMouseEntered

    private void back_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseExited
        reset(back_bttn);
    }//GEN-LAST:event_back_bttnMouseExited

    private void logout_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseClicked
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_bttnMouseClicked

    private void logout_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseEntered
        set(logout_bttn);
    }//GEN-LAST:event_logout_bttnMouseEntered

    private void logout_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseExited
        reset(logout_bttn);
    }//GEN-LAST:event_logout_bttnMouseExited
private void set(JPanel panel){
    panel.setBackground(new Color(0,153,204));
    }
    
    private void reset(JPanel panel){
    panel.setBackground(new Color(0,102,51));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printreceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back_bttn;
    private javax.swing.JPanel edit_bttn;
    private javax.swing.JPanel home_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_cheque;
    private javax.swing.JPanel logout_bttn;
    private javax.swing.JPanel print_option;
    private javax.swing.JPanel search_bttn;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_amountword;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cgstamount;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_coursename;
    private javax.swing.JLabel txt_coursename1;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel txt_receiptno;
    private javax.swing.JLabel txt_receivedfrom;
    private javax.swing.JLabel txt_semester;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_sgstamount;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    private javax.swing.JPanel viewrecord_bttn;
    // End of variables declaration//GEN-END:variables
}
