/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.fee;

import cms.Home;
import cms.numbertoword;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaibhav
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        Connect();
        updatecourcecombo();
        
    }
    /************************************************************************************************************************/
     Connection con;
         PreparedStatement pst;
         ResultSet rs;
         DefaultTableModel d;
           public void Connect()
            {
              try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(editreceipt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(editreceipt.class.getName()).log(Level.SEVERE, null, ex);
        } 
            }
    /********************************************************************************************************************/
public void updatecourcecombo(){
 try{
         pst=con.prepareStatement("SELECT * from cource");
             rs=pst.executeQuery();
             while(rs.next()){
                cource_combo.addItem(rs.getString("courcename"));
             }
      }catch(Exception e){
      }
}
/********************************************************************************************************************/
public void tableupdate(){
    String cource=cource_combo.getSelectedItem().toString();
    String sem=semester_combo.getSelectedItem().toString();
    SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
    String fromdate=df.format(datechooser_fromdate.getDate());
    String todate=df.format(datechooser_todate.getDate());
    
    Float amt=0.0f;
try{
         pst=con.prepareStatement("select * from fees where date between ? and ? and course_name=? and semester=?");   /*between clause is used...first ? represent from date*/
           pst.setString(1, fromdate);
           pst.setString(2, todate);
           pst.setString(3, cource);
           pst.setString(4, sem);
         rs=pst.executeQuery();
             while(rs.next()){
                String receipt=rs.getString("receipt_no");
                String studentname=rs.getString("student_name");
                String rollno=rs.getString("roll_no");
                String courcename=rs.getString("course_name");
                String semester=rs.getString("semester");
                float amount=rs.getFloat("total_amount");
                String paymentmode=rs.getString("payment_mode");
                
                amt=amt+amount;
                
                Object[] obj={receipt,studentname,rollno,courcename,semester,amount,paymentmode };
                d=(DefaultTableModel)search_table.getModel();
                d.addRow(obj);
             }
             lbl_courcename.setText(cource);
             lbl_semester.setText(sem);
             lbl_amount.setText(amt.toString());
             lbl_amountword.setText(numbertoword.convert(amt.intValue())); /*convert the wrapper  class float value in interger value*/
      }catch(Exception e){
      }
}
/********************************************************************************************************************/
  public void cleartable(){
   d=(DefaultTableModel)search_table.getModel();
   d.setRowCount(0);
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        home_bttn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search_bttn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        print_option = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        edit_bttn = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        viewrecord_bttn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        back_bttn = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        logout_bttn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datechooser_fromdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        datechooser_todate = new com.toedter.calendar.JDateChooser();
        submit_bttn = new javax.swing.JButton();
        print_bttn = new javax.swing.JButton();
        cource_combo = new javax.swing.JComboBox<>();
        semester_combo = new javax.swing.JComboBox<>();
        total = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_amountword = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_courcename = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        lbl_semester = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 102, 51));
        sidebar.setForeground(new java.awt.Color(0, 204, 51));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_bttn.setBackground(new java.awt.Color(0, 102, 51));
        home_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_bttnMouseExited(evt);
            }
        });
        home_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        home_bttn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");
        home_bttn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 40));

        sidebar.add(home_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 70));

        search_bttn.setBackground(new java.awt.Color(0, 102, 51));
        search_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        search_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_bttnMouseExited(evt);
            }
        });
        search_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/search2.png"))); // NOI18N
        search_bttn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search Record");
        search_bttn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 30));

        sidebar.add(search_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 70));

        print_option.setBackground(new java.awt.Color(0, 102, 51));
        print_option.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print_option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_optionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_optionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print_optionMouseExited(evt);
            }
        });
        print_option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/printer-.png"))); // NOI18N
        jLabel30.setText("Print");
        print_option.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 70));

        sidebar.add(print_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 70));

        edit_bttn.setBackground(new java.awt.Color(0, 102, 51));
        edit_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_bttnMouseExited(evt);
            }
        });
        edit_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit2.png"))); // NOI18N
        jLabel29.setText("Edit");
        edit_bttn.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, -1));

        sidebar.add(edit_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, 70));

        viewrecord_bttn.setBackground(new java.awt.Color(0, 102, 51));
        viewrecord_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewrecord_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        viewrecord_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseExited(evt);
            }
        });
        viewrecord_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/list_1.png"))); // NOI18N
        viewrecord_bttn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("View Record");
        viewrecord_bttn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(viewrecord_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 190, 70));

        back_bttn.setBackground(new java.awt.Color(0, 102, 51));
        back_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        back_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_bttnMouseExited(evt);
            }
        });
        back_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/left-arrow.png"))); // NOI18N
        back_bttn.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Back");
        back_bttn.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 190, 70));

        logout_bttn.setBackground(new java.awt.Color(0, 102, 51));
        logout_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        logout_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_bttnMouseExited(evt);
            }
        });
        logout_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        logout_bttn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Logout");
        logout_bttn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(logout_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 190, 70));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 720));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_table.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Receipt_No", "Student Name", "Roll_No", "Cource_Name", "Semester", "Amount", "Payment Mode"
            }
        ));
        search_table.setOpaque(false);
        jScrollPane1.setViewportView(search_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1040, 440));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("From Date :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select Semester");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select Date :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 30));
        jPanel1.add(datechooser_fromdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("To Date :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 90, 30));
        jPanel1.add(datechooser_todate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 140, 30));

        submit_bttn.setText("Submit");
        submit_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 30));

        print_bttn.setText("Print");
        print_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(print_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 30));

        cource_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Select Cource-----" }));
        jPanel1.add(cource_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 240, 30));

        semester_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Select Semester------", "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6" }));
        jPanel1.add(semester_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, 30));

        total.setBackground(new java.awt.Color(0, 153, 153));
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 3));
        total.setOpaque(false);
        total.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount in words :");
        total.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 30));

        lbl_amountword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_amountword.setForeground(new java.awt.Color(255, 255, 255));
        lbl_amountword.setText("amount words");
        total.add(lbl_amountword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 430, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Amount :");
        total.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cource Selected :");
        total.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 30));

        lbl_courcename.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_courcename.setForeground(new java.awt.Color(255, 255, 255));
        lbl_courcename.setText("Cource Selected ");
        total.add(lbl_courcename, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 30));

        lbl_amount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_amount.setForeground(new java.awt.Color(255, 255, 255));
        lbl_amount.setText("Amount");
        total.add(lbl_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, 30));

        lbl_semester.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_semester.setForeground(new java.awt.Color(255, 255, 255));
        lbl_semester.setText("semster");
        total.add(lbl_semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Semester :");
        total.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 30));

        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 450, 230));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Select Cource");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1120, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void set(JPanel panel){
    panel.setBackground(new Color(0,153,204));
    }
    
    private void reset(JPanel panel){
    panel.setBackground(new Color(0,102,51));
    }
    private void submit_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_bttnActionPerformed
      cleartable();
        tableupdate();
    }//GEN-LAST:event_submit_bttnActionPerformed

    private void print_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_bttnActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("YYYY-MM-dd");
        String fromdate=sdf.format(datechooser_fromdate.getDate());
          String todate=sdf.format(datechooser_todate.getDate());
          
          MessageFormat header=new MessageFormat("Report From "+fromdate+" To " +todate);
          MessageFormat footer=new MessageFormat("page{0,number,integer}");
          try{
             search_table.print(JTable.PrintMode.FIT_WIDTH,header,footer);
          }catch(Exception e){
            e.getMessage();
          }
    }//GEN-LAST:event_print_bttnActionPerformed

    private void home_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseClicked
        fees_menu fm=new fees_menu();
        fm.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_bttnMouseClicked

    private void home_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseEntered
        set(home_bttn);

    }//GEN-LAST:event_home_bttnMouseEntered

    private void home_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseExited
        reset(home_bttn);
    }//GEN-LAST:event_home_bttnMouseExited

    private void search_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bttnMouseClicked
        search_fee_records sfr=new search_fee_records();
        sfr.setVisible(true);
        dispose();
    }//GEN-LAST:event_search_bttnMouseClicked

    private void search_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bttnMouseEntered
        set(search_bttn);
    }//GEN-LAST:event_search_bttnMouseEntered

    private void search_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_bttnMouseExited
        reset(search_bttn);
    }//GEN-LAST:event_search_bttnMouseExited

    private void print_optionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseClicked
        printreceipt pr=new printreceipt();
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_print_optionMouseClicked

    private void print_optionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseEntered
        set(print_option);
    }//GEN-LAST:event_print_optionMouseEntered

    private void print_optionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseExited
        reset(print_option);
    }//GEN-LAST:event_print_optionMouseExited

    private void edit_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseClicked
        editreceipt er=new editreceipt();
        er.setVisible(true);
        dispose();
    }//GEN-LAST:event_edit_bttnMouseClicked

    private void edit_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseEntered
        set(edit_bttn);
    }//GEN-LAST:event_edit_bttnMouseEntered

    private void edit_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseExited
        reset(edit_bttn);
    }//GEN-LAST:event_edit_bttnMouseExited

    private void viewrecord_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseClicked
        viewrecords vr=new viewrecords();
        vr.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewrecord_bttnMouseClicked

    private void viewrecord_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseEntered
        set(viewrecord_bttn);
    }//GEN-LAST:event_viewrecord_bttnMouseEntered

    private void viewrecord_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseExited
        reset(viewrecord_bttn);
    }//GEN-LAST:event_viewrecord_bttnMouseExited

    private void back_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseClicked
        fees_menu f=new fees_menu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_bttnMouseClicked

    private void back_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseEntered
        set(back_bttn);
    }//GEN-LAST:event_back_bttnMouseEntered

    private void back_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseExited
        reset(back_bttn);
    }//GEN-LAST:event_back_bttnMouseExited

    private void logout_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseClicked
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_bttnMouseClicked

    private void logout_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseEntered
        set(logout_bttn);
    }//GEN-LAST:event_logout_bttnMouseEntered

    private void logout_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseExited
        reset(logout_bttn);
    }//GEN-LAST:event_logout_bttnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back_bttn;
    private javax.swing.JComboBox<String> cource_combo;
    private com.toedter.calendar.JDateChooser datechooser_fromdate;
    private com.toedter.calendar.JDateChooser datechooser_todate;
    private javax.swing.JPanel edit_bttn;
    private javax.swing.JPanel home_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_amountword;
    private javax.swing.JLabel lbl_courcename;
    private javax.swing.JLabel lbl_semester;
    private javax.swing.JPanel logout_bttn;
    private javax.swing.JButton print_bttn;
    private javax.swing.JPanel print_option;
    private javax.swing.JPanel search_bttn;
    private javax.swing.JTable search_table;
    private javax.swing.JComboBox<String> semester_combo;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton submit_bttn;
    private javax.swing.JPanel total;
    private javax.swing.JPanel viewrecord_bttn;
    // End of variables declaration//GEN-END:variables
}
