/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.fee;

import cms.Home;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vaibhav
 */
public class search_fee_records extends javax.swing.JFrame {

    /**
     * Creates new form search_fee_records
     */
    public search_fee_records() {
        initComponents();
        Connect();
        updatetable();
    }
/************************************************************************************************************************/
     Connection con;
         PreparedStatement pst;
         ResultSet rs;
         DefaultTableModel d;
           public void Connect()
            {
              try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(editreceipt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(editreceipt.class.getName()).log(Level.SEVERE, null, ex);
        } 
            }
    /********************************************************************************************************************/
    public void updatetable(){
      try{
         pst=con.prepareStatement("SELECT * from fees");
             rs=pst.executeQuery();
             while(rs.next()){
                 String Receipt_No=rs.getString("receipt_no");
                 String StudentName=rs.getString("student_name");
                 String Roll_No=rs.getString("roll_no");
                 String Cource_Name=rs.getString("course_name");
                 String Semester=rs.getString("semester");
                 float Amount=rs.getFloat("amount");
                 String PaymentMode=rs.getString("Payment_mode");
                Object[] obj={Receipt_No,StudentName,Roll_No,Cource_Name,Semester,Amount,PaymentMode};
                d=(DefaultTableModel)search_table.getModel();
                d.addRow(obj);
             }
      }catch(Exception e){
      
      }
    }
    /********************************************************************************************************************/
    public void search(String str){
    d=(DefaultTableModel)search_table.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(d); /**sort and filter the table for search*/
    search_table.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        home_bttn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        print_option = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        edit_bttn = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        viewrecord_bttn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        back_bttn = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        logout_bttn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchtab = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 102, 51));
        sidebar.setForeground(new java.awt.Color(0, 204, 51));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_bttn.setBackground(new java.awt.Color(0, 102, 51));
        home_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_bttnMouseExited(evt);
            }
        });
        home_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        home_bttn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");
        home_bttn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 40));

        sidebar.add(home_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 70));

        print_option.setBackground(new java.awt.Color(0, 102, 51));
        print_option.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print_option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_optionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_optionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print_optionMouseExited(evt);
            }
        });
        print_option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/printer-.png"))); // NOI18N
        jLabel30.setText("Print");
        print_option.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 70));

        sidebar.add(print_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 70));

        edit_bttn.setBackground(new java.awt.Color(0, 102, 51));
        edit_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_bttnMouseExited(evt);
            }
        });
        edit_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit2.png"))); // NOI18N
        jLabel29.setText("Edit");
        edit_bttn.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, -1));

        sidebar.add(edit_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 70));

        viewrecord_bttn.setBackground(new java.awt.Color(0, 102, 51));
        viewrecord_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewrecord_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        viewrecord_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewrecord_bttnMouseExited(evt);
            }
        });
        viewrecord_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/list_1.png"))); // NOI18N
        viewrecord_bttn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("View Record");
        viewrecord_bttn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(viewrecord_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 190, 70));

        back_bttn.setBackground(new java.awt.Color(0, 102, 51));
        back_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        back_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_bttnMouseExited(evt);
            }
        });
        back_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/left-arrow.png"))); // NOI18N
        back_bttn.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Back");
        back_bttn.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 190, 70));

        logout_bttn.setBackground(new java.awt.Color(0, 102, 51));
        logout_bttn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_bttn.setMinimumSize(new java.awt.Dimension(150, 70));
        logout_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_bttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_bttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_bttnMouseExited(evt);
            }
        });
        logout_bttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        logout_bttn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Logout");
        logout_bttn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        sidebar.add(logout_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 190, 70));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 720));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_table.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt_No", "Student Name", "Roll_No", "Cource_Name", "Semester", "Amount", "Payment Mode"
            }
        ));
        search_table.setOpaque(false);
        jScrollPane1.setViewportView(search_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1040, 560));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search Record");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Search String :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        searchtab.setBackground(new java.awt.Color(21, 25, 28));
        searchtab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchtab.setForeground(new java.awt.Color(51, 51, 255));
        searchtab.setBorder(null);
        searchtab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtabKeyReleased(evt);
            }
        });
        jPanel1.add(searchtab, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 510, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 480, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1060, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void set(JPanel panel){
    panel.setBackground(new Color(0,153,204));
    }
    
    private void reset(JPanel panel){
    panel.setBackground(new Color(0,102,51));
    }
    private void searchtabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtabKeyReleased
        String search=searchtab.getText();
        search(search);
    }//GEN-LAST:event_searchtabKeyReleased

    private void home_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseClicked
        fees_menu fm=new fees_menu();
        fm.setVisible(true);
        dispose();
    }//GEN-LAST:event_home_bttnMouseClicked

    private void home_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseEntered
        set(home_bttn);

    }//GEN-LAST:event_home_bttnMouseEntered

    private void home_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_bttnMouseExited
        reset(home_bttn);
    }//GEN-LAST:event_home_bttnMouseExited

    private void print_optionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseClicked
        printreceipt pr=new printreceipt();
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_print_optionMouseClicked

    private void print_optionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseEntered
        set(print_option);
    }//GEN-LAST:event_print_optionMouseEntered

    private void print_optionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_optionMouseExited
        reset(print_option);
    }//GEN-LAST:event_print_optionMouseExited

    private void edit_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseClicked
        editreceipt er=new editreceipt();
        er.setVisible(true);
        dispose();
    }//GEN-LAST:event_edit_bttnMouseClicked

    private void edit_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseEntered
        set(edit_bttn);
    }//GEN-LAST:event_edit_bttnMouseEntered

    private void edit_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_bttnMouseExited
        reset(edit_bttn);
    }//GEN-LAST:event_edit_bttnMouseExited

    private void viewrecord_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseClicked
        viewrecords vr=new viewrecords();
        vr.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewrecord_bttnMouseClicked

    private void viewrecord_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseEntered
        set(viewrecord_bttn);
    }//GEN-LAST:event_viewrecord_bttnMouseEntered

    private void viewrecord_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewrecord_bttnMouseExited
        reset(viewrecord_bttn);
    }//GEN-LAST:event_viewrecord_bttnMouseExited

    private void back_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseClicked
        fees_menu f=new fees_menu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_bttnMouseClicked

    private void back_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseEntered
        set(back_bttn);
    }//GEN-LAST:event_back_bttnMouseEntered

    private void back_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_bttnMouseExited
        reset(back_bttn);
    }//GEN-LAST:event_back_bttnMouseExited

    private void logout_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseClicked
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_bttnMouseClicked

    private void logout_bttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseEntered
        set(logout_bttn);
    }//GEN-LAST:event_logout_bttnMouseEntered

    private void logout_bttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_bttnMouseExited
        reset(logout_bttn);
    }//GEN-LAST:event_logout_bttnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_fee_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_fee_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_fee_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_fee_records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_fee_records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back_bttn;
    private javax.swing.JPanel edit_bttn;
    private javax.swing.JPanel home_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logout_bttn;
    private javax.swing.JPanel print_option;
    private javax.swing.JTable search_table;
    private javax.swing.JTextField searchtab;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel viewrecord_bttn;
    // End of variables declaration//GEN-END:variables
}
