/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.login;

import cms.Home;
import cms.forgetpass;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vaibhav
 */
public class LoginForm extends javax.swing.JFrame {
public String gender;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        Connect();
         this.setLocationRelativeTo(null);
        jPanel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_uname = new javax.swing.JTextField();
        create_user = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        forgetpass = new javax.swing.JLabel();
        sign_in = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txt_contact = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        pass_view = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        utype = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        minimize_bttn = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        view_pass = new javax.swing.JCheckBox();
        txttype = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_uname.setBackground(new java.awt.Color(31, 36, 42));
        txt_uname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_uname.setForeground(new java.awt.Color(153, 153, 153));
        txt_uname.setText("Enter Username");
        txt_uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_uname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt_unameMouseMoved(evt);
            }
        });
        txt_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_unameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_unameFocusLost(evt);
            }
        });
        txt_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 205, 260, 40));

        create_user.setBackground(new java.awt.Color(169, 224, 49));
        create_user.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        create_user.setForeground(new java.awt.Color(169, 224, 49));
        create_user.setText("Create New User");
        create_user.setBorder(null);
        create_user.setBorderPainted(false);
        create_user.setContentAreaFilled(false);
        create_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create_user.setRequestFocusEnabled(false);
        create_user.setVerifyInputWhenFocusTarget(false);
        create_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_userActionPerformed(evt);
            }
        });
        jPanel1.add(create_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 90));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 30, 45));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, 45));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setText("Userrname");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 90, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(169, 224, 49));
        jLabel20.setText("Password");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, -1));

        forgetpass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        forgetpass.setForeground(new java.awt.Color(169, 224, 49));
        forgetpass.setText("Forget Password?");
        forgetpass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgetpassMouseMoved(evt);
            }
        });
        forgetpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetpassMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgetpassMousePressed(evt);
            }
        });
        jPanel1.add(forgetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 140, -1));

        sign_in.setBackground(new java.awt.Color(152, 201, 45));
        sign_in.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sign_in.setForeground(new java.awt.Color(21, 25, 28));
        sign_in.setText("Sign In");
        sign_in.setBorder(null);
        sign_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_in.setFocusPainted(false);
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        jPanel1.add(sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 260, 40));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_logo.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cllg_logo.gif"))); // NOI18N
        jPanel3.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 314, 260));

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_contact.setBackground(new java.awt.Color(31, 36, 42));
        txt_contact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_contact.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt_contactMouseMoved(evt);
            }
        });
        jPanel6.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 330, 30));

        lname.setBackground(new java.awt.Color(31, 36, 42));
        lname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        lname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lnameMouseMoved(evt);
            }
        });
        jPanel6.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 160, 30));

        mail.setBackground(new java.awt.Color(31, 36, 42));
        mail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        mail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mailMouseMoved(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        jPanel6.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 330, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel12.setText("And");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 40, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(169, 224, 49));
        jLabel14.setText("Contact Number");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 130, 20));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(169, 224, 49));
        jLabel15.setText("Last Name");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 90, 20));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(169, 224, 49));
        jLabel18.setText("Gender");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, -1));

        create.setBackground(new java.awt.Color(152, 201, 45));
        create.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        create.setForeground(new java.awt.Color(21, 25, 28));
        create.setText("Sign up");
        create.setBorder(null);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.setFocusPainted(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel6.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-cllg.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 140, 130));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 224, 49));
        jLabel13.setText("Advanced Technology");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 180, -1));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(169, 224, 49));
        jLabel22.setText("Kamal Institute Of Higher Education");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 300, -1));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(169, 224, 49));
        jLabel21.setText("Email");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 314, 20));

        pass.setBackground(new java.awt.Color(31, 36, 42));
        pass.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel6.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 330, 30));

        back.setBackground(new java.awt.Color(169, 224, 49));
        back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(169, 224, 49));
        back.setText("Back");
        back.setBorder(null);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setRequestFocusEnabled(false);
        back.setVerifyInputWhenFocusTarget(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel6.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 110, -1));

        pass_view.setBackground(new java.awt.Color(152, 201, 45));
        pass_view.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pass_view.setForeground(new java.awt.Color(255, 255, 255));
        pass_view.setText("show");
        pass_view.setBorder(null);
        pass_view.setBorderPainted(true);
        pass_view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pass_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_viewActionPerformed(evt);
            }
        });
        jPanel6.add(pass_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 90, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(169, 224, 49));
        jLabel17.setText("First Name");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 20));

        fname.setBackground(new java.awt.Color(31, 36, 42));
        fname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        fname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fnameMouseMoved(evt);
            }
        });
        jPanel6.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 30));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel16.setText("Username");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 90, 20));

        txt_username.setBackground(new java.awt.Color(31, 36, 42));
        txt_username.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_username.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt_usernameMouseMoved(evt);
            }
        });
        jPanel6.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 330, 30));

        utype.setBackground(new java.awt.Color(31, 36, 42));
        utype.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        utype.setForeground(new java.awt.Color(255, 255, 255));
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Teacher" }));
        utype.setBorder(null);
        utype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        utype.setOpaque(false);
        jPanel6.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 110, -1));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(169, 224, 49));
        jLabel23.setText("Password");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 314, -1));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(169, 224, 49));
        jLabel24.setText("Usertype");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 80, -1));

        female.setBackground(new java.awt.Color(152, 201, 45));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel6.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        male.setBackground(new java.awt.Color(152, 201, 45));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel6.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 500, 620));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_reed.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        minimize_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        minimize_bttn.setToolTipText("Minimize");
        minimize_bttn.setBorder(null);
        minimize_bttn.setBorderPainted(false);
        minimize_bttn.setContentAreaFilled(false);
        minimize_bttn.setFocusPainted(false);
        minimize_bttn.setRequestFocusEnabled(false);
        minimize_bttn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus_red.png"))); // NOI18N
        minimize_bttn.setVerifyInputWhenFocusTarget(false);
        minimize_bttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_bttnMouseClicked(evt);
            }
        });
        minimize_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimize_bttnActionPerformed(evt);
            }
        });
        jPanel3.add(minimize_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 520, 670));

        txt_pass.setBackground(new java.awt.Color(31, 36, 42));
        txt_pass.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 305, 260, 40));

        view_pass.setBackground(new java.awt.Color(152, 201, 45));
        view_pass.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        view_pass.setForeground(new java.awt.Color(255, 255, 255));
        view_pass.setText("show");
        view_pass.setBorder(null);
        view_pass.setBorderPainted(true);
        view_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_passActionPerformed(evt);
            }
        });
        jPanel1.add(view_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 90, -1));

        txttype.setBackground(new java.awt.Color(31, 36, 42));
        txttype.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txttype.setForeground(new java.awt.Color(255, 255, 255));
        txttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Admin", "Teacher" }));
        txttype.setBorder(null);
        txttype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txttype.setOpaque(false);
        jPanel1.add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 110, -1));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(169, 224, 49));
        jLabel25.setText("Usertype");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/cms", "root", "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    Home h=new Home();
    private void txt_unameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_unameMouseMoved

    }//GEN-LAST:event_txt_unameMouseMoved

    private void txt_unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unameFocusGained
        if (txt_uname.getText().equals("Enter Username")) {
            txt_uname.setText("");
            txt_uname.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txt_unameFocusGained

    private void txt_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unameActionPerformed

    private void create_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_userActionPerformed
        jLabel_logo.setVisible(false);

        jPanel6.setVisible(true);
        // jLabel17.setVisible(false);
        // jLabel18.setVisible(false);
    }//GEN-LAST:event_create_userActionPerformed

    private void forgetpassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassMouseMoved
        forgetpass.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_forgetpassMouseMoved

    private void forgetpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassMouseClicked
      forgetpass fp=new forgetpass();
      fp.setVisible(true);
    }//GEN-LAST:event_forgetpassMouseClicked

    private void forgetpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassMousePressed

    }//GEN-LAST:event_forgetpassMousePressed

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed

        String username = txt_uname.getText();
        String password = txt_pass.getText();
        String usertype=txttype.getSelectedItem().toString();
        try {
            pst = con.prepareStatement("select * from signin where username=? and password=? and usertype=?");
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, usertype);
            rs = pst.executeQuery();
            if (rs.next()) {
                
                 int id=rs.getInt("id");
                this.dispose();
                new Home(id,username,usertype).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or Password");
                txt_uname.setText("");
                txt_pass.setText("");
                txttype.setSelectedIndex(-1);
                txt_uname.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sign_inActionPerformed

    private void txt_contactMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contactMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactMouseMoved

    private void lnameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameMouseMoved

    private void mailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_mailMouseMoved

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
         String usertype=utype.getSelectedItem().toString();
        String firstname = fname.getText();
        String lastname = lname.getText();
        String email = mail.getText();
        String contact=txt_contact.getText();
        String username = txt_username.getText();
        String password = pass.getText();
        try {
            pst = con.prepareStatement("insert into signin (usertype,firstname,lastname,gender,email,contact,username,password)values(?,?,?,?,?,?,?,?);");
            pst.setString(1, usertype);
            pst.setString(2, firstname);
            pst.setString(3, lastname);
            pst.setString(4, gender);
            pst.setString(5, email);
            pst.setString(6, contact);
            pst.setString(7, username);
            pst.setString(8, password);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "You Have Successfully Signup!!");
            jPanel6.setVisible(false);
            jLabel_logo.setVisible(true);
            /**
            * coding for clearing the form fname.setText("");
            * lname.setText(""); mail.setText(""); txt_user.setText("");
            * security_ques.setSelectedIndex(-1); security_ans.setText("");
            * pass.setText(""); fname.requestFocus();
            */

        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        jPanel6.setVisible(false);
        jLabel_logo.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void pass_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_viewActionPerformed
        if (pass_view.isSelected()) {
            pass.setEchoChar((char) 0);
        } else {
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_pass_viewActionPerformed

    private void fnameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameMouseMoved

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed

    }//GEN-LAST:event_txt_passKeyPressed

    private void view_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_passActionPerformed
        if (view_pass.isSelected()) {
            txt_pass.setEchoChar((char) 0);
        } else {
            txt_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_view_passActionPerformed

    private void txt_unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_unameFocusLost
         if (txt_uname.getText().equals("")) {
            txt_uname.setText("Enter Username");
            txt_uname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_unameFocusLost

    private void txt_usernameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameMouseMoved

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
 
         gender="male";
        
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
     
         gender="female";
        
    }//GEN-LAST:event_femaleActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void minimize_bttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_bttnMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimize_bttnMouseClicked

    private void minimize_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimize_bttnActionPerformed

    }//GEN-LAST:event_minimize_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton create;
    private javax.swing.JButton create_user;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel forgetpass;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton minimize_bttn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JCheckBox pass_view;
    private javax.swing.JButton sign_in;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_uname;
    private javax.swing.JTextField txt_username;
    private javax.swing.JComboBox<String> txttype;
    private javax.swing.JComboBox<String> utype;
    private javax.swing.JCheckBox view_pass;
    // End of variables declaration//GEN-END:variables
}
