/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.student;

import cms.student.studentform;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author vaibhav
 */
public class editstudent extends javax.swing.JFrame {
public String gender;
 String path=null;
byte[] userimage=null;
    /**
     * Creates new form editstudent
     */
    public editstudent() {
        initComponents();
        Connect();
      
    }

    Connection con;
         PreparedStatement pst;
         ResultSet rs;
       
           public void Connect()
            {
              try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3307/college_management" , "root" , "mysql");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(editstudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(editstudent.class.getName()).log(Level.SEVERE, null, ex);
        } 
            }
   /*****************************************************************************************************************/        
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        txt_mail = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_image = new javax.swing.JLabel();
        choose_pic_bttn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_doa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_roll = new javax.swing.JTextField();
        lbl_cource = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_mother = new javax.swing.JTextField();
        txt_father = new javax.swing.JTextField();
        txt_moccupation = new javax.swing.JTextField();
        txt_foccupation = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Student Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 80));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, -1));

        txt_search.setBackground(new java.awt.Color(21, 25, 28));
        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_search.setForeground(new java.awt.Color(51, 51, 255));
        txt_search.setBorder(null);
        txt_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_searchFocusLost(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Personal Details");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(153, 153, 153));
        txt_fname.setText("Firstname");
        txt_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fnameFocusLost(evt);
            }
        });
        jPanel3.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, 40));

        txt_lname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_lname.setForeground(new java.awt.Color(153, 153, 153));
        txt_lname.setText("Lastname");
        txt_lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lnameFocusLost(evt);
            }
        });
        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 220, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Of Birth");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        female.setBackground(new java.awt.Color(152, 201, 45));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(152, 201, 45));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        male.setBackground(new java.awt.Color(152, 201, 45));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(152, 201, 45));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel3.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        txt_mail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(153, 153, 153));
        txt_mail.setText("Email");
        txt_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mailFocusLost(evt);
            }
        });
        jPanel3.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 40));

        txt_address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_address.setForeground(new java.awt.Color(153, 153, 153));
        txt_address.setText("Address");
        txt_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_addressFocusLost(evt);
            }
        });
        jPanel3.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, 90));

        txt_phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(153, 153, 153));
        txt_phone.setText("Contact Number");
        txt_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_phoneFocusLost(evt);
            }
        });
        jPanel3.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 30));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopPane1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 180));

        jPanel3.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, 200));

        choose_pic_bttn.setBackground(new java.awt.Color(152, 201, 45));
        choose_pic_bttn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        choose_pic_bttn.setText("Choose Pic");
        choose_pic_bttn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        choose_pic_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_pic_bttnActionPerformed(evt);
            }
        });
        jPanel3.add(choose_pic_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 20));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 580, 400));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("School Details");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(31, 36, 42));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_doa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_doa.setForeground(new java.awt.Color(153, 153, 153));
        txt_doa.setText("Date Of Admission (dd/mm/yyyy)");
        txt_doa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_doaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_doaFocusLost(evt);
            }
        });
        jPanel4.add(txt_doa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cource");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txt_roll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_roll.setForeground(new java.awt.Color(153, 153, 153));
        txt_roll.setText("Roll Number");
        txt_roll.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rollFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rollFocusLost(evt);
            }
        });
        jPanel4.add(txt_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 30));

        lbl_cource.setBackground(new java.awt.Color(31, 36, 42));
        lbl_cource.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_cource.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lbl_cource, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 350, 140));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Parent's Details");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jPanel5.setBackground(new java.awt.Color(31, 36, 42));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_mother.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_mother.setForeground(new java.awt.Color(153, 153, 153));
        txt_mother.setText("Mother's  name");
        txt_mother.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_motherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_motherFocusLost(evt);
            }
        });
        jPanel5.add(txt_mother, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 330, 30));

        txt_father.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_father.setForeground(new java.awt.Color(153, 153, 153));
        txt_father.setText("Father's name");
        txt_father.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fatherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fatherFocusLost(evt);
            }
        });
        jPanel5.add(txt_father, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 30));

        txt_moccupation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_moccupation.setForeground(new java.awt.Color(153, 153, 153));
        txt_moccupation.setText("Occupation");
        txt_moccupation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_moccupationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_moccupationFocusLost(evt);
            }
        });
        jPanel5.add(txt_moccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 330, 30));

        txt_foccupation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_foccupation.setForeground(new java.awt.Color(153, 153, 153));
        txt_foccupation.setText("Occupation");
        txt_foccupation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_foccupationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_foccupationFocusLost(evt);
            }
        });
        jPanel5.add(txt_foccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 30));

        txt_contact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(153, 153, 153));
        txt_contact.setText("Contact No");
        txt_contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contactFocusLost(evt);
            }
        });
        jPanel5.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 350, 220));

        update.setBackground(new java.awt.Color(152, 201, 45));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setText("Update");
        update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 110, -1));

        cancel.setBackground(new java.awt.Color(152, 201, 45));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 980, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusGained
        if (txt_fname.getText().equals("Firstname")) {
            txt_fname.setText("");
            txt_fname.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_fnameFocusGained

    private void txt_fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusLost
        if (txt_fname.getText().equals("")) {
            txt_fname.setText("Firstname");
            txt_fname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_fnameFocusLost

    private void txt_lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusGained
        if (txt_lname.getText().equals("Lastname")) {
            txt_lname.setText("");
            txt_lname.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_lnameFocusGained

    private void txt_lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusLost
        if (txt_lname.getText().equals("")) {
            txt_lname.setText("Lastname");
            txt_lname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_lnameFocusLost

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender="female";
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender="male";
    }//GEN-LAST:event_maleActionPerformed

    private void txt_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusGained
        if (txt_mail.getText().equals("Email")) {
            txt_mail.setText("");
            txt_mail.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_mailFocusGained

    private void txt_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mailFocusLost
        if (txt_mail.getText().equals("")) {
            txt_mail.setText("Email");
            txt_mail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_mailFocusLost

    private void txt_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusGained
        if (txt_address.getText().equals("Address")) {
            txt_address.setText("");
            txt_address.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_addressFocusGained

    private void txt_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusLost
        if (txt_address.getText().equals("")) {
            txt_address.setText("Address");
            txt_address.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_addressFocusLost

    private void txt_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusGained
        if (txt_phone.getText().equals("Contact Number")) {
            txt_phone.setText("");
            txt_phone.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_phoneFocusGained

    private void txt_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_phoneFocusLost
        if (txt_phone.getText().equals("")) {
            txt_phone.setText("Contact Number");
            txt_phone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_phoneFocusLost

    private void choose_pic_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_pic_bttnActionPerformed
        JFileChooser picchooser=new JFileChooser();
        picchooser.setDialogTitle("Select Image");
        picchooser.showOpenDialog(null);
        File pic=picchooser.getSelectedFile();
        path= pic.getAbsolutePath();
        ImageIcon icon=new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
        lbl_image.setIcon(icon);
        try{
            File image = new File(path);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos= new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for(int readNum; (readNum=fis.read(buff)) !=-1 ; ){
                baos.write(buff,0,readNum);
            }
            userimage=baos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_choose_pic_bttnActionPerformed

    private void txt_doaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_doaFocusGained
        if (txt_doa.getText().equals("Date Of Admission (dd/mm/yyyy)")) {
            txt_doa.setText("");
            txt_doa.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_doaFocusGained

    private void txt_doaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_doaFocusLost
        if (txt_doa.getText().equals("")) {
            txt_doa.setText("Date Of Admission (dd/mm/yyyy)");
            txt_doa.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_doaFocusLost

    private void txt_rollFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rollFocusGained
        if (txt_roll.getText().equals("Roll Number")) {
            txt_roll.setText("");
            txt_roll.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_rollFocusGained

    private void txt_rollFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rollFocusLost
        if (txt_roll.getText().equals("")) {
            txt_roll.setText("Roll Number");
            txt_roll.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_rollFocusLost

    private void txt_motherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_motherFocusGained
        if (txt_mother.getText().equals("Mother's  name")) {
            txt_mother.setText("");
            txt_mother.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_motherFocusGained

    private void txt_motherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_motherFocusLost
        if (txt_mother.getText().equals("")) {
            txt_mother.setText("Mother's  name");
            txt_mother.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_motherFocusLost

    private void txt_fatherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fatherFocusGained
        if (txt_father.getText().equals("Father's name")) {
            txt_father.setText("");
            txt_father.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_fatherFocusGained

    private void txt_fatherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fatherFocusLost
        if (txt_father.getText().equals("")) {
            txt_father.setText("Father's name");
            txt_father.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_fatherFocusLost

    private void txt_moccupationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_moccupationFocusGained
        if (txt_moccupation.getText().equals("Occupation")) {
            txt_moccupation.setText("");
            txt_moccupation.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_moccupationFocusGained

    private void txt_moccupationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_moccupationFocusLost
        if (txt_moccupation.getText().equals("")) {
            txt_moccupation.setText("Occupation");
            txt_moccupation.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_moccupationFocusLost

    private void txt_foccupationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_foccupationFocusGained
        if (txt_foccupation.getText().equals("Occupation")) {
            txt_foccupation.setText("");
            txt_foccupation.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_foccupationFocusGained

    private void txt_foccupationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_foccupationFocusLost
        if (txt_foccupation.getText().equals("")) {
            txt_foccupation.setText("Occupation");
            txt_foccupation.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_foccupationFocusLost

    private void txt_contactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactFocusGained
        if (txt_contact.getText().equals("Contact No")) {
            txt_contact.setText("");
            txt_contact.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_contactFocusGained

    private void txt_contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactFocusLost
        if (txt_contact.getText().equals("")) {
            txt_contact.setText("Contact No");
            txt_contact.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_contactFocusLost

    private void txt_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusGained
        if (txt_search.getText().equals("Enter Student Rollno")) {
            txt_search.setText("");
            txt_search.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_searchFocusGained

    private void txt_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_searchFocusLost
        if (txt_search.getText().equals("")) {
            txt_search.setText("Enter Student Rollno");
            txt_search.setForeground(new Color(51,51,255));
        }
    }//GEN-LAST:event_txt_searchFocusLost

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
     
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           String rollno=txt_search.getText();
           try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
            pst=con.prepareStatement("select * from students where rollno='"+rollno+"'");
            rs=pst.executeQuery();
            if(rs.next()){
                txt_fname.setText(rs.getString("firstname"));
                txt_lname.setText(rs.getString("lastname"));
                jTextField1.setText(rs.getString("dob"));
                String gender=rs.getString("gender");
                if(gender.equals("male")){
                   male.setSelected(true);
                }else{
                   female.setSelected(true);
                }
                txt_mail.setText(rs.getString("email"));
                txt_address.setText(rs.getString("address"));
                txt_phone.setText(rs.getString("contact"));
                byte[] path=rs.getBytes("pic");
                 ImageIcon icon=new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
                  lbl_image.setIcon(icon);
                  txt_doa.setText(rs.getString("admissiondate"));
                  txt_roll.setText(rs.getString("rollno"));
                 lbl_cource.setText(rs.getString("cource"));
                  txt_father.setText(rs.getString("fathername"));
                  txt_foccupation.setText(rs.getString("fatheroccupation"));
                  txt_mother.setText(rs.getString("mothername"));
                  txt_moccupation.setText(rs.getString("motheroccupation"));
                  txt_contact.setText(rs.getString("parent_contact"));   
            }
            else
            JOptionPane.showMessageDialog(null, "Student Record Not Found!!!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error in connection");
        }
       }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String firstname=txt_fname.getText();
       String lastname=txt_lname.getText();
       String dob=jTextField1.getText();
       String email=txt_mail.getText();
       String address=txt_address.getText();
       String contact=txt_phone.getText();
       String admissiondate=txt_doa.getText();
       String rollno=txt_roll.getText();
       String cource=lbl_cource.getText();
       String fathername=txt_father.getText();
       String fatheroccupation=txt_foccupation.getText();
       String mothername=txt_mother.getText();
       String motheroccupation=txt_moccupation.getText();
       String parent_contact=txt_contact.getText();
       
    try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3307/cms" , "root" , "mysql");
            Statement st=con.createStatement();
            rs=st.executeQuery("select * from students where rollno='"+rollno+"'");
            if(rs.next())
            {
                st.executeUpdate("update students set firstname='"+firstname+"' , lastname='"+lastname+"', dob='"+dob+"' , email='"+email+"' , contact='"+contact+"', admissiondate='"+admissiondate+"', address='"+address+"', cource='"+cource+"', fathername='"+fathername+"', fatheroccupation='"+fatheroccupation+"', mothername='"+mothername+"', motheroccupation='"+motheroccupation+"', parent_contact='"+parent_contact+"' where rollno='"+rollno+"'");
                JOptionPane.showMessageDialog(null,"Student Details Updated Successfully!!");
                setVisible(false);
                new studentform().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"NO STUDENT RECORD FOUND!!!");

            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
            
    }//GEN-LAST:event_updateActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        studentform sf=new studentform();
        sf.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JButton choose_pic_bttn;
    private javax.swing.JRadioButton female;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_cource;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_doa;
    private javax.swing.JTextField txt_father;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_foccupation;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_moccupation;
    private javax.swing.JTextField txt_mother;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_roll;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
